name: app-build-action-manual

on:
  workflow_dispatch: # 开启网页手动触发按钮
  push:
    branches:
      - master # 提交到 master 分支时自动编译

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      # 1. 签出代码
      - uses: actions/checkout@v4
        with:
          ref: master

      # 2. 设置 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      # 3. 更新依赖
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # 4. 直接开始打包 iOS (免证书)
      - name: Build IPA
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      # 5. 创建未签名 ipa
      - name: Create IPA
        run: |
          cd simple_live_app
          mkdir build/ios/iphoneos/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos/
          zip -q -r ios_no_sign.ipa Payload

      # 6. 上传未签名 IPA 至网页端供下载
      - name: Upload IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: simple_live_app/build/ios/iphoneos/ios_no_sign.ipa
